Repository go-vgo/robotgo, pull requests merged in 2021-08, with the labels that each got.

#348 Update README.md Section ####Other to windows
  README.md
Labels: Linux, update

#349 Update README.md and Update Dockerfile and go.yml
  .circleci/images/primary/Dockerfile
  .github/workflows/go.yml
  README.md
  README_zh.md
  appveyor.yml
Labels: enhancement, update

#350 add windows arm support [step 1]
  .gitignore
  base/png_io_c.h
  cdeps/win/amd/win32/libpng.a
  cdeps/win/amd/win32/png.h
  cdeps/win/amd/win32/pngconf.h
  cdeps/win/amd/win32/pnglibconf.h
  cdeps/win/amd/win32/zconf.h
  cdeps/win/amd/win32/zlib.h
  cdeps/win/amd/win64/libpng.a
  cdeps/win/amd/win64/png.h
  cdeps/win/amd/win64/pngconf.h
  cdeps/win/amd/win64/pnglibconf.h
  cdeps/win/amd/win64/zconf.h
  cdeps/win/amd/win64/zlib.h
  robotgo.go
Labels: enhancement, Windows

#352 This fixes the disappearing backslash issue
  robotgo.go
Labels: Linux

#353 Export ToUC function and update test code
  robotgo.go
  robotgo_test.go
Labels: update

#354 Fixes #258: char* arrays in C not being copied correctly
  window/window.h
Labels: bug, Linux

#355 Fixed Linux TypeStr() function input double quote
  robotgo.go
Labels: bug, Linux

#356 Update go mod and circle.yml
  .circleci/config.yml
  .travis.yml
  examples/window/main.go
  go.mod
  go.sum
Labels: update
