Repository go-vgo/robotgo, pull requests merged in 2024-10, with the labels that each got.

#691 Update: move scale to screen and rename pub mdata
  screen/screen_c.h
  window/goWindow.h
  window/pub.h
  window/win_sys.h
  window/window.h
Labels: update

#692 Fixed: default use high capture resolution in macos15
  screen.go
  screen/goScreen.h
  screen/screengrab_c.h
Labels: enhancement

#663 capture error
  robotgo.go
Labels: update

#693 Update: update screen capture code and examples
  .circleci/images/primary/Dockerfile
  README.md
  examples/screen/main.go
  robotgo.go
  robotgo_test.go
  screen.go
Labels: enhancement, update

#694 Update: update readme.md
  README.md
Labels: update

#695 Update: update go mod
  go.mod
  go.sum
Labels: update
